### PR TITLE
Fix examples

### PR DESCRIPTION
**Pull request by KCeh**
Most of the issues were caused by outdated JSON response type (PoV < 4.0.0) or invalid JSON issues. There were also minor issues in the code.
All examples should work now.

### CODE REVIEW

**Comment by KCeh** [comment]
Looks like we have CI issues. 
I don't have access to take a look, but I guess things might be out of date.

**Comment by JonatanPlesko** [comment]
> I don't have access to take a look, but I guess things might be out of date.

I gave the entire Android team Developer access (I think this makes sense), and you should also have Admin access specifically to manage workflows.

**Comment by KCeh** [comment]
There is an issue with connecting the project to Github or SSH keys

Build fails with error:
```
Warning: Permanently added 'github.com,140.82.113.3' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

In settings:
image

Since I am not sure how Github integration with Bitrise is configured I think it is best for LEs to check it.

**Comment by simicmarin** [comment]
@antunflas Please check if ssh key is included into Infinum-fastlane account.

**Comment by antunflas** [comment]
CI has been fixed.

**Comment by KCeh** [comment]
@antunflas I will just merge this as no "real" changes are present and PR is open for some time

**Pull request merged**
